# Generated by Django 5.2.3 on 2025-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('potholes', 'Potholes'), ('garbage', 'Garbage'), ('streetlight', 'Streetlight'), ('water', 'Water')], default='potholes', max_length=20),
        ),
    ]
