# Generated by Django 5.2.3 on 2025-09-06 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_lat_lng'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='issue',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
