# Generated by Django 5.2.3 on 2025-09-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_remove_issue_upvotes_issue_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='issue',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
